services:
  talker:
    build:
      dockerfile: Dockerfile.chatter
    command: ros2 run demo_nodes_cpp talker

  foxglove-bridge:
    build:
      dockerfile: Dockerfile
      context: ../
    ports:
      - 8765:8765
    command: ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765

  foxglove:
    image: husarion/foxglove:1.72.0
    ports:
      - 8080:8080
    volumes:
      - ./foxglove_layout.json:/foxglove/default-layout.json
    environment:
      - DS_TYPE=foxglove-websocket
      - DS_PORT=8765
      - UI_PORT=8080
